### ISSUE TITLE
Sugerencia 

### ISSUE THREAD

**Issue by Dantesinferno11** [hezqiel7/JkAnime-Downloader#1]
Hola me gustaría saber si es posible que hagas una app con la extensión de jkanime para descargar capítulos de jkanime, no sé mucho sobre cómo usar la extensión y estoy seguro que mucha personas les resultaría más fácil con una app. Gracias

**Comment by hezqiel7** [comment]
Hola.
Gracias por tu sugerencia, pero actualmente no puedo asumir nuevos proyectos. Si estás intentando descargar desde tu teléfono, puedo recomendarte que descargues Kiwi Browser, con él se pueden instalar extensiones. Podrás instalar la extensión sin ningún problema.
Si tienes alguna otra pregunta o necesitas más ayuda, no dudes en decírmelo.
