### ISSUE TITLE
Jkanime downloader dejó de funcionar 

### ISSUE THREAD

**Issue by Dantesinferno11** [hezqiel7/JkAnime-Downloader#2]
Dejo de funcionar en mi pc, ya no descarga nada, reinstale la extensión pero ni aun así funciono. Esta muy buena la extensión solo que por ahora no funciona.

**Comment by hezqiel7** [comment]
Dejó de funcionar porque JkAnime ya quitó la opción de descarga desde su propio servidor, que era lo que estaba usando la extensión. Ahora solo hay opciones de descarga de otros servicios (mega, 1fitcher, etc.) que lamentablemente ya no se pueden integrar con la extensión, así que de momento no hay solución.
